on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Install package
        run: pip install '.[test,ja]'
      
      - name: Run tests
        run: pytest tests
